apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: finance
  name: myapp-deployment-1
  labels:
    app: myapp-deployment-1

spec:
  template:
    metadata:
      name: myapp-busybox-pod
      labels:
        app: myapp-busybox

    spec:
      containers:
        - name: busybox-container
          image: busybox
  replicas: 3
  selector:
    matchLabels:
      app: myapp-busybox
  resources:
    requests:
      memory: "1Gi"
               cpu: .5
            limits:
              memory: "2Gi"
              cpu: 1
  replicas: 2
  selector:
    matchLabels:
      app: beta-pod