apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels: 
    tier: dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app2
  template:
    metadata:
      labels:
        app: my-app2
    spec:
      containers:
      - name: task2-container
        image: nginx

