kind: Pod 
apiVersion: v1 
metadata:
  name: webapp-color
spec:
  containers:
    - name: webapp-color-container
      image: nginx:1.7.9 
      envFrom:
        - configMapRef:
            name: webapp-config-map
