apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  volumes:
    - name: pv-log
      persistentVolumeClaim:
        claimName: claim-log-1
  containers:
    - name: task-pv-container
      image: nginx
      volumeMounts:
        - mountPath: "/usr/log/nginx"
          name: pv-log



