FROM jenkins/jenkins:lts-jdk11

USER root

RUN apt-get update -qq \
    && apt-get install -qqy apt-transport-https ca-certificates curl gnupg2 software-properties-common

# Adding docker repo
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

# Updating the apt repos
RUN apt-get update  -qq 

# Installing docker
RUN apt-get install docker-ce -y
RUN usermod -aG docker jenkins
RUN service docker start

# Installing kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl



# RUN mkdir /var/jenkins_home2

# RUN apt-get update 
# RUN apt-get install ca-certificates 
# RUN apt-get install curl
# RUN apt-get install gnupg
# RUN apt-get install lsb-release -y
# RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg |   gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

# RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" |   tee /etc/apt/sources.list.d/docker.list > /dev/null
# RUN apt-get update 
# RUN apt-get install docker-ce docker-ce-cli containerd.io -y