FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
COPY docker-entrypoint.sh /usr/local/bin

#ENTRYPOINT ["docker-entrypoint.sh"]
RUN chmod 777 /usr/local/bin/docker-entrypoint.sh && ln -s /usr/local/bin/docker-entrypoint.sh 
RUN npm install
RUN apt update && apt install -y mysql
#RUN docker-machine env
#RUN SET DOCKER_HOST=tcp://172.17.0.1
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 3000

CMD [ "node", "app.js" ]
