FROM httpd:2.4

#WORKDIR /usr/src/app

#COPY package*.json ./
COPY index.html /usr/local/apache2/htdocs/
#RUN apt-get update
#RUN apt-get install -y npm

#COPY . .

EXPOSE 9999
#CMD [ "node", "server.
